name: CI

on: [push,pull_request]

jobs:
  build:

    runs-on: macos-10.15
    
    steps:
    - uses: actions/checkout@v1
    - name: Run unit test
      run: |
        pod install --repo-update
        xcodebuild test -workspace ShadowsocksX-NG.xcworkspace -scheme ShadowsocksX-NG | xcpretty
