name: CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [macos-10.15, macos-11]

    
    steps:
    - uses: actions/checkout@v1
    - name: Run unit test
      run: |
        pod install --repo-update
        xcodebuild test -workspace ShadowsocksX-NG.xcworkspace -scheme ShadowsocksX-NG | xcpretty
